# This is a basic workflow to help you get started with Actions

name: "Continuous Delivery Microservices"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_run:
    workflows: ["Continuous Integration Tests"]
    branches: [master]
    paths:
      - 'src/**'
      - 'account/**'
      - 'card/**'
      - 'conf/**'
      - 'funds/**'
      - 'loans/**'
      - 'docker-compose.yml'
      - 'Dockerfile'
      - 'Cargo.toml'
      - 'makefile'
      - 'Dockerfile.account'
      - 'Dockerfile.card'
      - 'Dockerfile.core'
    types: 
      - completed

  workflow_dispatch:


jobs:
  deploy:

    runs-on: ubuntu-latest
    # Timeout of 30 minutes to deploy with docker-compose
    timeout-minutes: 30


    steps:

      - uses: actions/checkout@v2
      
      
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_SECRET }}
          #key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            whoami
            pwd
            echo "Geting remote ls"
            ls -al
            echo "Remove files remote and clone repo"
            docker-compose down -v && rm -rf cloudbanking/ && git clone https://github.com/pepitoenpeligro/cloudbanking/
            cd cloudbanking/
            ls -al
            pwd
            echo "Build and compose containers"
            docker-compose up -d 
            echo "[Delivery] END"

      # - name: Test Remote Docker-Compose
      #   run: |
      #     echo "Getting list of investments in Funds Microservice. Should be empty"
      #     curl --location --request GET "http://pepecordoba.site:80/funds"
      #     echo "Creating a new invertment in Funds Microservice"
      #     curl --location --request POST "http://pepecordoba.site:80/funds" \
      #     --header 'Content-Type: application/json' \
      #     --data-raw '{ \
      #         "id" : 10, \
      #         "amount": 544.4, \
      #         "dateStart": "toady", \
      #         "dateEnd": "tomorrow", \
      #         "status": true \
      #     }' 
      #     echo "Getting list of investments in Funds Microservice. Should have one with id 10 and 554.4 amount"
      #     curl --location --request GET "http://pepecordoba.site:80/funds"
      #     echo "End Test"
